### ISSUE TITLE
Possibility of adding PQIs and PDIs?

### ISSUE THREAD

**Issue by samiaab1990** [wenjie2wang/touch#2]
Hi there,
I'm not sure if this would be outside the scope of the goals of this package, but do you think that the package could have the possibility of integrating PQIs and PDIs in it, analogous to the SAS QI software (https://qualityindicators.ahrq.gov/Software/Default.aspx)?

I got started on writing a script to output an .xlsx file to use in R that can be used to match PQIs with ICD-10 codes if merged with the dataset of interest (https://github.com/samiaab1990/AHRQ-PQI-Cleanup), but I am envisioning simplifying this more so that the dataset of interest can be input into a function and output the PQIs/PDIs. Wanted to check if this could be a potential feature of this package.

**Comment by wenjie2wang** [comment]
I am not familiar with PQIs or PDIs.  But they seem to be great features.  Contribution to {touch} is welcome.  I am not sure if it is straightforward to integrate and maintain them.  Another possibility is to create another package for PQIs and PDIs.

**Comment by samiaab1990** [comment]
Thank you for the feedback! I will work on this more and see if this would best belong in this package or a package of its own.
