### ISSUE TITLE
Run ICD code conversion using command line

### ISSUE THREAD

**Issue by baxtree** [wenjie2wang/touch#3]
Hi, thank you for creating and maintaining this package. Not really an "issue" for this and I didn't find a place for discussions so be this plugging-in post. I created a thin wrapper for `touch` to run the conversion between ICD-9 and ICD-10 codes via CLIs and used it in one of our benchmarking tasks. If you have a chance to have a look, any comments or feedback is welcome: [icd_code_converter](https://github.com/baxtree/icd_code_converter). Feel free to close this issue.

**Comment by wenjie2wang** [comment]
@baxtree Glad that you find this package useful.  The script you wrote looks good to me.
